ci: travis osx homebrew fix
Travis reported:

Error: HOMEBREW_LOGS was not exported!
Please don't worry, you likely hit a bug auto-updating from an old version.
Rerun your command, everything is up-to-date and fine now.