frontend/android: bump gradle, compileSdk and docker CI
- Gradle 8.0 -> 8.4
- Android Gradle Plugin 8.0.1 -> 8.3.0
- Build Tool 33.0.0 -> 34.0.0
- CompileSdk 33 -> 34

About `gem install dotenv -v 2.8.1` in docker_install.sh: this is needed
to fix the following error

```
+ gem install --no-document fpm
ERROR:  Error installing fpm:
	The last version of dotenv (>= 0) to support your Ruby & RubyGems
        was 2.8.1. Try installing it with `gem install dotenv -v 2.8.1`
        and then running the current command again
	dotenv requires Ruby version >= 3.0. The current ruby version
        is 2.7.0.0.
```